researchers:
- &lefebvre
  last: Lefebvre
  first: Bertrand
- &smith
  last: Smith
  first: A. B.
- &sumrall
  last: Sumrall
  first: Colin D.
- &zamora
  last: Zamora
  first: Samuel
- &zhu-x-j
  last: Zhu
  first: Xue-Jian
journals:
- &geomag Geological Magazine
- &procrsocb Proceedings of the Royal Society B
rocks:
- &murero-fmtn
  name: Murero Formation
  place: [Purujosa, Moncayo National Park, Spain]
  local: [Caesaraugustan, Lower Languedocian]
- &coulouma
  name: Coulouma
  place: [Montagne Noir, France]
  local: [Caesaraugustan, Lower Languedocian]
- &sandu-fmtn
  name: Sandu Formation
  place: [Guole Town, Jingxi County, Guangxi Province, China]
  landmass: South China
  time: [Stage 9, Furongian, Cambrian]
taxon:
- &aethocrinus
  name: Aethocrinus
  auth: [Ubaghs]
  year: 1969
- &akadocrinus
  name: Akadocrinus
  auth: [Prokop]
  year: 1962
- &barroubiocystis
  name: Barroubiocystis
  auth: [Ubaghs]
  year: 1999
- &blastozoa
  name: Blastozoa
  rank: Subphylum
  auth: [Sprinkle]
  year: 1973
- &cheirocrinus
  name: Cheirocrinus
  auth: [Eichwald]
  year: 1856
- &cheirocystis
  name: Cheirocystis
  auth: [Paul]
  year: 1972
- &crinoidea
  name: Crinoidea
  rank: Class
  auth: [Miller]
  year: 1821
- &crinozoa
  name: Crinozoa
  rank: Subphylum
  auth: [Matsumoto]
  year: 1929
- &cuniculocystis
  name: Cuniculocystis
  auth: [Sprinkle, Wahlman]
  year: 1994
- &dibrachycystidae
  name: Dibrachycystidae
  rank: Family
  auth: [Zamora, Smith]
  year: 2012
- &dibrachycystis
  name: Dibrachycystis
  auth: [Zamora, Smith]
  year: 2012
- &echinoencrinites
  name: Echinoencrinites
  auth: [von Meyer]
  year: 1826
- &echinodermata
  name: Echinodermata
  rank: Phylum
  status: monophyletic
  auth: [Bruguière]
  year: 1791
  ex:
    auth: [Klein]
    year: 1743
- &eocystites
  name: Eocystites
  auth: [Billings]
  year: 1868
- &glyptocystites
  name: Glyptocystites
  auth: [Billings]
  year: 1854
- &glyptocystitida
  name: Glyptocystitida
  rank: Order
  auth: [Bather]
  year: 1899
- &gogia
  name: Gogia
  auth: [Walcott]
  year: 1917
- &hemicosmites
  name: Hemicosmites
  auth: [Buch]
  year: 1840
- &kinzercystis
  name: Kinzercystis
  auth: [Sprinkle]
  year: 1973
- &languedocianus
  name: languedocianus
  auth: [Ubaghs]
  year: 1987
- &lepadocystis
  name: Lepadocystis
  auth: [Carpenter]
  year: 1891
- &lyracystis
  name: Lyracystis
  auth: [Sprinkle, Collins]
  year: 2006
- &macrocystella
  name: Macrocystella
  auth: [Callaway]
  year: 1877
- &moncaiensis
  name: moncaiensis
  auth: [Zamora, Smith]
  year: 2012
- &pelmatozoa
  name: Pelmatozoa
  rank: Subphylum
  status: informal
  auth: [Leuckart]
  year: 1848
- &pleurocystites
  name: Pleurocystites
  auth: [Neumayr]
  year: 1899
- &purujoensis
  name: purujoensis
  auth: [Zamora, Smith]
  year: 2012
- &rhombifera
  name: Rhombifera
  rank: class
  status: informal
  auth: [Zittel]
  year: 1870
- &ridersia
  name: Ridersia
  auth: [Jell, Burrett, Banks]
  year: 1985
- &sanducystis
  name: Sanducystis
  auth: [Zamora, Sumrall, Zhu, Lefebvre]
  year: 2017
- &scoliocystis
  name: Scoliocystis
  auth: [Jaekel]
  year: 1899
- &sinensis
  name: sinensis
  auth: [Zamora, Sumrall, Zhu, Lefebvre]
  year: 2017
- &sinoeocrinus
  name: Sinoeocrinus
  auth: [Zhao, Huang, Gong]
  year: 1994
- &stephanocrinus
  name: Stephanocrinus
  auth: [Conrad]
  year: 1842
- &tatonkacystis
  name: Tatonkacystis
  auth: [Sumrall, Sprinkle, Guensburg]
  year: 1997
- &titanocrinus
  name: Titanocrinus
  auth: [Guensburg, Sprinkle]
  year: 2003
- &ubaghsicystis
  name: Ubaghsicystis
  auth: [Gil Cid, Domínguez]
  year: 2002
- &velieuxicystis
  name: Velieuxicystis
  auth: [Ubaghs]
  year: 1999
- &vizcainoia
  name: Vizcainoia
  auth: [Zamora, Smith]
  year: 2012
synonyms:
- &eocrinus
  name: Eocrinus
  auth: [Jaekel]
  year: 1918
  synonym: *gogia
articles:
- title: A new stemmed echinoderm from the Furongian of China and the origin of Glyptocystitida (Blastozoa, Echinodermata)
  dates:
    received: 2015-11-17
    accepted: 2016-01-27
    online: 2016-03-03
  journal:
    name: *geomag
    volume: 154
    number: 3
    pubdate: 2017
    pages:
    - 465
    - 475
  doi: 10.1017/S001675681600011X
  authors:
  - *zamora
  - *sumrall
  - *zhu-x-j
  - *lefebvre
  taxonomy:
    definitions:
    - - taxon: *echinodermata
        children:
        - taxon: *blastozoa
          children:
          - taxon: *rhombifera
            quoted: true
            children:
            - taxon: *glyptocystitida
              children:
              - taxon: *sanducystis
                new: true
                children:
                - taxon: *sinensis
                  new: true
                  place: *sandu-fmtn
    inferences:
    - - taxon: *echinodermata
        children:
        - taxon: *blastozoa
          children:
          - taxon: *rhombifera
            quoted: true
            children:
            - taxon: *glyptocystitida
              children:
              - taxon: *ridersia
  phylogeny:
  - children:
    - bracket: *glyptocystitida
      children:
      - taxon: *ridersia
      - children:
        - taxon: *sanducystis
        - children:
          - children:
            - taxon: *macrocystella
            - taxon: *cuniculocystis
            - children:
              - children:
                - children:
                  - taxon: *pleurocystites
                  - children:
                    - taxon: *lepadocystis
                    - taxon: *scoliocystis
                    - taxon: *echinoencrinites
                - taxon: *cheirocystis
                - taxon: *glyptocystites
              - taxon: *cheirocrinus
          - taxon: *barroubiocystis
          - taxon: *velieuxicystis
    - taxon: *stephanocrinus
    - taxon: *hemicosmites
- title: Cambrian stalked echinoderms show unexpected plasticity of arm construction
  dates:
    received: 2011-04-13
    accepted: 2011-05-19
    online: 2011-06-08
  journal:
    name: *procrsocb
    volume: 279
    pubdate: 2012
    pages:
    - 293
    - 298
  doi: 10.1098/rspb.2011.0777
  authors:
  - *zamora
  - *smith
  taxonomy:
    definitions:
    - - taxon: *echinodermata
        children:
        - taxon: *rhombifera
          rank: Plesion
          children:
          - taxon: *dibrachycystidae
            new: true
            children:
            - taxon: *dibrachycystis
              new: true
              children:
              - taxon: *purujoensis
                new: true
                place: *murero-fmtn
            - taxon: *vizcainoia
              new: true
              children:
              - taxon: *languedocianus
                place: *murero-fmtn
              - taxon: *moncaiensis
                new: true
                place: *coulouma
  phylogeny:
  - taxon: *kinzercystis
    children:
    - children:
      - taxon: *gogia
      - taxon: *sinoeocrinus
      - children:
        - children:
          - children:
            - children:
              - taxon: *ridersia
              - taxon: *macrocystella
            - taxon: *velieuxicystis
          - taxon: *pleurocystites
          - taxon: *dibrachycystis
        - taxon: *akadocrinus
    - children:
      - taxon: *lyracystis
        children:
        - *titanocrinus
        - *aethocrinus
