researchers:
- &gibson
  family: Gibson
  given: Adam P.
- &lefebvre
  family: Lefebvre
  given: Bertrand
- &parsley
  family: Parsley
  given: Ronald
- &rahman
  family: Rahman
  given: Imran A.
- &smith
  family: Smith
  given: Andrew B.
- &sumrall
  family: Sumrall
  given: Colin D.
- &thompson
  family: Thompson
  given: Jeffrey R.
- &zamora
  family: Zamora
  given: Samuel
- &zhao-y-l
  family: Zhao
  given: Yuanlong
- &zhu-x-j
  family: Zhu
  given: Xue-Jian
journals:
- &geomag Geological Magazine
- &jofpaleo Journal of Paleontology
- &procrsocb Proceedings of the Royal Society B
rocks:
- &coulouma
  name: Coulouma
  place: [Montagne Noir, France]
  local: [[Caesaraugustan, Lower Languedocian]]
- &jbel-wawrmast-fmtn
  name: Jbel Wawrmast Formation
  place: [Alnif region, eastern Anti-Atlas mountains, Morocco]
- &jince-fmtn
  name: Jince Formation
  place: [Prague Basin, Bohemia]
  time: [Middle Cambrian, Cambrian]
- &kaili-fmtn
  name: Kaili Formation
  place: [Miaobapo Quarry, Jianhe County, Guizhou Province, China]
  landmass: South China
  time: [Stage 4, Miaolingian, Cambrian]
  notes: '"middle third" of the formation, basal Middle Cambrian'
- &kinzers-fmtn
  name: Kinzers Formation
  place: [York, Pennsylvania, United States]
  local: [[middle Dyeran Stage, Delemaran Stage]]
  time: [Stage 4, Miaolingian, Cambrian]
- &murero-fmtn
  name: Murero Formation
  place: [Purujosa, Moncayo National Park, Spain]
  local: [Caesaraugustan, Lower Languedocian]
- &sandu-fmtn
  name: Sandu Formation
  place: [Guole Town, Jingxi County, Guangxi Province, China]
  landmass: South China
  time: [Stage 9, Furongian, Cambrian]
- &breche-a-micmacca-member
  name: Brèche à Micmacca Member
  time: [517MA, Stage 3, Series 2, Cambrian]
  formation: *jbel-wawrmast-fmtn
- &tarhoucht-member
  name: Tarhoucht Member
  time: [[515MA, 510MA], Stage 4, Series 2, Cambrian]
  formation: *jbel-wawrmast-fmtn
- &emmigsville-member
  name: Emmigsville Member
  formation: *kinzers-fmtn
taxon:
- &aethocrinus
  name: Aethocrinus
  auth: [Ubaghs]
  year: 1969
- &akadocrinus
  name: Akadocrinus
  auth: [Prokop]
  year: 1962
- &apektocrinus
  name: Apektocrinus
  auth: [Guensburg, Sprinkle]
  year: 2009
- &argodiscus
  name: Argodiscus
  auth: [Prokop]
  year: 1965
- &asturicystis
  name: Asturicystis
  auth: [Sdzuy]
  year: 1993
- &barroubiocystis
  name: Barroubiocystis
  auth: [Ubaghs]
  year: 1999
- &blastozoa
  name: Blastozoa
  rank: Subphylum
  bracket: Blastozoans
  auth: [Sprinkle]
  year: 1973
- &camptostroma
  name: Camptostroma
  auth: [Ruedemann]
  year: 1933
- &castericystis
  name: Castericystis
  auth: [Ubaghs, Robison]
  year: 1985
- &cheirocrinus
  name: Cheirocrinus
  auth: [Eichwald]
  year: 1856
- &cheirocystis
  name: Cheirocystis
  auth: [Paul]
  year: 1972
- &courtessolea
  name: Courtessolea
  auth: [Domínguez-Alonso]
  year: 1989
- &crinoidea
  name: Crinoidea
  rank: Class
  auth: [Miller]
  year: 1821
- &crinozoa
  name: Crinozoa
  rank: Subphylum
  auth: [Matsumoto]
  year: 1929
- &cuniculocystis
  name: Cuniculocystis
  auth: [Sprinkle, Wahlman]
  year: 1994
- &dibrachycystidae
  name: Dibrachycystidae
  rank: Family
  auth: [Zamora, Smith]
  year: 2012
- &dibrachycystis
  name: Dibrachycystis
  auth: [Zamora, Smith]
  year: 2012
- &echinoencrinites
  name: Echinoencrinites
  auth: [von Meyer]
  year: 1826
- &echinodermata
  name: Echinodermata
  rank: Phylum
  status: monophyletic
  auth: [Bruguière]
  year: 1791
  ex:
    auth: [Klein]
    year: 1743
- &edrioasteroidea
  name: Edrioasteroidea
  rank: Class
  bracket: Edrioasteroids
  auth: [Billings]
  year: 1858
- &eocrinoidea
  name: Eocrinoidea
  rank: Class
  bracket: Eocrinoids
  status: informal
  auth: [Jaekel]
  year: 1918
- &eocystites
  name: Eocystites
  auth: [Billings]
  year: 1868
- &glyptocystites
  name: Glyptocystites
  auth: [Billings]
  year: 1854
- &glyptocystitida
  name: Glyptocystitida
  bracket: Glyptocystitids
  rank: Order
  auth: [Bather]
  year: 1899
- &gogia
  name: Gogia
  auth: [Walcott]
  year: 1917
- &gogiida
  name: Gogiida
  bracket: Gogiids
  rank: Order
  auth: [Broadhead]
  year: 1982
- &haefneri
  name: haefneri
  auth: [Zamora, Rahman, Sumrall, Gibson, Thompson]
  year: 2022
- &helicocystoidea
  name: Helicocystoidea
  bracket: Helicocystoids
  rank: Class
  status: unregistered
  notes: |
    "Helicocystoids" often mentioned, including by Zamora, and some authors
    mention "Helicocystoidea" credited to Smith and Zamora 2013, but the paper
    only defines the family, genus, and species, and no formal class definition
    has been found.
  auth: [Smith, Zamora]
  year: 2013
- &helicocystitidae
  name: Helicocystitidae
  rank: Family
  auth: [Smith, Zamora]
  year: 2013
- &helicocystis
  name: Helicocystis
  auth: [Smith, Zamora]
  year: 2013
- &helicoplacoidea
  name: Helicoplacoidea
  bracket: Helicoplacoids
  rank: Class
  auth: [Durham, Caster]
  year: 1963
- &helicoplacus
  name: Helicoplacus
  auth: [Durham, Caster]
  year: 1963
- &hemicosmites
  name: Hemicosmites
  auth: [Buch]
  year: 1840
- &inflatus
  name: inflatus
  auth: [Parsley, Zhao]
  year: 2010
- &isorophus
  name: Isorophus
  auth: [Foerste]
  year: 1916
- &kinzercystis
  name: Kinzercystis
  auth: [Sprinkle]
  year: 1973
- &languedocianus
  name: languedocianus
  auth: [Ubaghs]
  year: 1987
- &lepadocystis
  name: Lepadocystis
  auth: [Carpenter]
  year: 1891
- &lepidocystis
  name: Lepidocystis
  auth: [Foerste]
  in: [Resser, Howell]
  year: 1938
- &lyracystis
  name: Lyracystis
  auth: [Sprinkle, Collins]
  year: 2006
- &macrocystella
  name: Macrocystella
  auth: [Callaway]
  year: 1877
- &moncaiensis
  name: moncaiensis
  auth: [Zamora, Smith]
  year: 2012
- &moroccoensis
  name: moroccoensis
  auth: [Smith, Zamora]
  year: 2013
- &parsleya
  name: Parsleya
  auth: [Deshmukh]
  year: 2022
- &pelmatozoa
  name: Pelmatozoa
  bracket: Pelmatozoans
  rank: Subphylum
  status: informal
  auth: [Leuckart]
  year: 1848
- &pleurocystites
  name: Pleurocystites
  auth: [Neumayr]
  year: 1899
- &purujoensis
  name: purujoensis
  auth: [Zamora, Smith]
  year: 2012
- &rhombifera
  name: Rhombifera
  bracket: Rhombiferans
  rank: class
  status: informal
  auth: [Zittel]
  year: 1870
- &ridersia
  name: Ridersia
  auth: [Jell, Burrett, Banks]
  year: 1985
- &sanducystis
  name: Sanducystis
  auth: [Zamora, Sumrall, Zhu, Lefebvre]
  year: 2017
- &scoliocystis
  name: Scoliocystis
  auth: [Jaekel]
  year: 1899
- &sinensis
  name: sinensis
  auth: [Zamora, Sumrall, Zhu, Lefebvre]
  year: 2017
- &sinoeocrinus
  name: Sinoeocrinus
  auth: [Zhao, Huang, Gong]
  year: 1994
- &stephanocrinus
  name: Stephanocrinus
  auth: [Conrad]
  year: 1842
- &stromatocystites
  name: Stromatocystites
  auth: [Pompeckj]
  year: 1896
- &tatonkacystis
  name: Tatonkacystis
  auth: [Sumrall, Sprinkle, Guensburg]
  year: 1997
- &titanocrinus
  name: Titanocrinus
  auth: [Guensburg, Sprinkle]
  year: 2003
- &turbanicystidae
  name: Turbanicystidae
  auth: [Parsley, Zhao]
  year: 2010
- &turbanicystis
  name: Turbanicystis
  auth: [Parsley, Zhao]
  year: 2010
- &ubaghsicystis
  name: Ubaghsicystis
  auth: [Gil Cid, Domínguez]
  year: 2002
- &velieuxicystis
  name: Velieuxicystis
  auth: [Ubaghs]
  year: 1999
- &vizcainoia
  name: Vizcainoia
  auth: [Zamora, Smith]
  year: 2012
- &vyscystis
  name: Vyscystis
  auth: [Fatka, Kordule]
  year: 1990
- &yorkicystitidae
  name: Yorkicystitidae
  rank: Family
  auth: [Zamora, Rahman, Sumrall, Gibson, Thompson]
  year: 2022
- &yorkicystis
  name: Yorkicystis
  auth: [Zamora, Rahman, Sumrall, Gibson, Thompson]
  year: 2022
synonyms:
- &eocrinus
  name: Eocrinus
  auth: [Jaekel]
  year: 1918
  synonym: *gogia
- &kailidiscus
  name: Kailidiscus
  auth: [Zhao, Sumrall, Parsley, Peng]
  year: 2010
  synonym: *parsleya
articles:
- title: A new stemmed echinoderm from the Furongian of China and the origin of Glyptocystitida (Blastozoa, Echinodermata)
  dates:
    received: 2015-11-17
    accepted: 2016-01-27
    online: 2016-03-03
  journal:
    name: *geomag
    volume: 154
    number: 3
    year: 2017
    pages:
    - 465
    - 475
  doi: 10.1017/S001675681600011X
  authors:
  - *zamora
  - *sumrall
  - *zhu-x-j
  - *lefebvre
  taxonomy:
    definitions:
    - taxon: *echinodermata
      children:
      - taxon: *blastozoa
        children:
        - taxon: *rhombifera
          quoted: true
          children:
          - taxon: *glyptocystitida
            children:
            - taxon: *sanducystis
              new: true
              children:
              - taxon: *sinensis
                new: true
                place: *sandu-fmtn
    inferences:
    - taxon: *echinodermata
      children:
      - taxon: *blastozoa
        children:
        - taxon: *rhombifera
          quoted: true
          children:
          - taxon: *glyptocystitida
            children:
            - taxon: *ridersia
  phylogeny:
  - children:
    - bracket: *glyptocystitida
      children:
      - taxon: *ridersia
      - children:
        - taxon: *sanducystis
        - children:
          - children:
            - taxon: *macrocystella
            - taxon: *cuniculocystis
            - children:
              - children:
                - children:
                  - taxon: *pleurocystites
                  - children:
                    - taxon: *lepadocystis
                    - taxon: *scoliocystis
                    - taxon: *echinoencrinites
                - taxon: *cheirocystis
                - taxon: *glyptocystites
              - taxon: *cheirocrinus
          - taxon: *barroubiocystis
          - taxon: *velieuxicystis
    - taxon: *stephanocrinus
      outgroup: true
    - taxon: *hemicosmites
      outgroup: true
- title: A New Turban-Shaped Gogiid Eocrinoid From The Kaili Formation (Kaili Biota), Balang, Jianhe County, Guizhou Province, China
  dates:
    accepted: 2009-11-29
  journal:
    name: *jofpaleo
    volume: 84
    number: 3
    year: 2010
    month: 5
    pages:
    - 549
    - 553
  jstor: 40605503
  taxonomy:
    definitions:
    - taxon: *echinodermata
      children:
      - taxon: *blastozoa
        children:
        - taxon: *eocrinoidea
          children:
          - taxon: *gogiida
            children:
            - taxon: *turbanicystidae
              new: true
              children:
              - taxon: *turbanicystis
                new: true
                children:
                - taxon: *inflatus
                  new: true
                  place: *kaili-fmtn
- title: Cambrian edrioasteroid reveals new mechanism for secondary reduction of the skeleton in echinoderms
  dates:
    received: 2021-12-17
    accepted: 2022-02-04
  journal:
    name: *procrsocb
    volume: 289
    year: 2022
    article: 20212733
  doi: 10.1098/rspb.2021.2733
  authors:
  - *zamora
  - *rahman
  - *sumrall
  - *gibson
  - *thompson
  taxonomy:
  - taxon: *echinodermata
    children:
    - taxon: *edrioasteroidea
      children:
      - taxon: *yorkicystitidae
        new: true
        children:
        - taxon: *yorkicystis
          new: true
          children:
          - taxon: *haefneri
            new: true
            place: *emmigsville-member
  phylogeny:
  - type: 50% majority-rule consenus Bayesian
    children:
    - children:
      - taxon: *helicocystis
      - children:
        - taxon: *lepidocystis
        - taxon: *vyscystis
        - children:
          - taxon: *titanocrinus
          - taxon: *apektocrinus
        - taxon: *ridersia
        - taxon: *gogia
        - taxon: *stromatocystites
        - children:
          - taxon: *kailidiscus
          - taxon: *yorkicystis
          - children:
            - taxon: *argodiscus
            - taxon: *isorophus
    - taxon: *helicoplacus
      outgroup: true
  - type: strict consensus of four most parsimonious trees parsimony analysis
    children:
    - children:
      - children:
        - bracket: *edrioasteroidea
          children:
          - children:
            - taxon: *kailidiscus
            - taxon: *yorkicystis
          - children:
            - taxon: *argodiscus
            - taxon: *isorophus
        - children:
          - children:
            - bracket: *blastozoa
              children:
              - taxon: *lepidocystis
              - taxon: *vyscystis
              - taxon: *ridersia
              - taxon: *gogia
            - bracket: *crinoidea
              children:
              - taxon: *titanocrinus
              - taxon: *apektocrinus
          - taxon: *stromatocystites
            bracket: *edrioasteroidea
      - taxon: *helicocystis
        bracket: *helicocystoidea
    - taxon: *helicoplacus
      bracket: *helicoplacoidea
      outgroup: true
- title: Cambrian spiral-plated echinoderms from Gondwana reveal the earliest pentaradial body plan
  dates:
    received: 2013-05-13
    accepted: 2013-06-04
    online: 2013-08-22
  journal:
    name: *procrsocb
    volume: 280
    year: 2013
    article: 20131197
  doi: 10.1098/rspb.2013.1197
  authors:
  - *smith
  - *zamora
  taxonomies:
  - taxon: *echinodermata
    stem: true
    children:
    - taxon: *helicocystitidae
      new: true
      children:
      - taxon: *helicocystis
        new: true
        children:
        - taxon: *moroccoensis
          new: true
          place: *jbel-wawrmast-fmtn
          time: [[515MA, 510MA], Stage 4, Series 2, Cambrian]
  phylogeny:
  - type: Evolutionary tree of Cambrian echinoderms
    children:
    - taxon: *courtessolea
    - children:
      - taxon: *asturicystis
      - children:
        - taxon: *castericystis
        - children:
          - taxon: *helicoplacus
          - children:
            - taxon: *helicocystis
            - children:
              - taxon: *camptostroma
              - children:
                - children:
                  - taxon: *lepidocystis
                  - taxon: *gogia
                - taxon: *stromatocystites
- title: Cambrian stalked echinoderms show unexpected plasticity of arm construction
  dates:
    received: 2011-04-13
    accepted: 2011-05-19
    online: 2011-06-08
  journal:
    name: *procrsocb
    volume: 279
    year: 2012
    pages:
    - 293
    - 298
  doi: 10.1098/rspb.2011.0777
  authors:
  - *zamora
  - *smith
  taxonomy:
    definitions:
    - taxon: *echinodermata
      children:
      - taxon: *rhombifera
        rank: Plesion
        children:
        - taxon: *dibrachycystidae
          new: true
          children:
          - taxon: *dibrachycystis
            new: true
            children:
            - taxon: *purujoensis
              new: true
              place: *murero-fmtn
          - taxon: *vizcainoia
            new: true
            children:
            - taxon: *languedocianus
              place: *murero-fmtn
            - taxon: *moncaiensis
              new: true
              place: *coulouma
  phylogeny:
  - taxon: *kinzercystis
    outgroup: true
    children:
    - children:
      - taxon: *gogia
      - taxon: *sinoeocrinus
      - children:
        - children:
          - children:
            - children:
              - taxon: *ridersia
              - taxon: *macrocystella
            - taxon: *velieuxicystis
          - taxon: *pleurocystites
          - taxon: *dibrachycystis
        - taxon: *akadocrinus
    - children:
      - taxon: *lyracystis
        children:
        - *titanocrinus
        - *aethocrinus
